Add a set of working VMware Fusion examples
hashicorp/packer-plugin-vmware pull request #130
Opened 2023-04-13 13:29 UTC by nywilken

This change adds a set of template examples for Fusion 13 and Fusion 12. These templates have been tested for both arm64 and x86_64 processors. 

The source files are spread across multiple files:
 - source.pkr.hcl contains the source block definition for the build image.
 - variables.pkr.hcl contains a set of defined variables need for building the image.
 - build.pkr.hcl is the main entry point for Packer to build the VMware image defined in source.pkr.hcl.
 - pkrvars/ contains a set of Packer variable definition files (*.pkrvars.hcl) partitioned by guest_os/vmware-version.

2023-04-13 14:48 UTC, tenthirtyam commented on example/README.md
> +as VMware Fusion, VMware Player, and VMware Workstation all work slightly different.
```suggestion
as VMware ESXi, VMware Fusion, VMware Player, and VMware Workstation all work slightly differently. 
```

2023-04-13 15:03 UTC, tenthirtyam commented on example/pkrvars/debian/fusion-12.pkrvars.hcl
Given that Fusion 12 is end-of-support, would it be better to only maintain only Fusion 13 example here?

2023-04-13 15:06 UTC, tenthirtyam commented on example/pkrvars/debian/fusion-13.pkrvars.hcl
Would it be better to only maintain Fusion 13 examples for:
- M1/2-based Macs - arm : `guest_os_type = "debian-64"`
- Intel-based Mac - x64: `guest_os_type = "arm-debian-64"`

2023-04-13 15:09 UTC, tenthirtyam commented on example/README.md
Would it be better to only maintain Fusion 13 examples for:
- M1/2-based Macs - arm : `guest_os_type = "debian-64"`
- Intel-based Mac - x64: `guest_os_type = "arm-debian-64"`

2023-04-13 15:10 UTC, tenthirtyam commented on example/README.md
Should this be `examples/` plural?

2023-04-13 15:12 UTC, tenthirtyam commented on example/http/debian/preseed.cfg
Might be nice to show how this can be done with a template like `ks.pkrtpl.hcl`.

An example I have authored for the vSphere plugin: https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/builds/linux/debian/11/data/ks.pkrtpl.hcl

2023-04-13 15:14 UTC, tenthirtyam requested changes
I've added some comments for consideration.

2023-04-13 19:36 UTC, nywilken commented on example/README.md
The plugin can use a  few driver updates to make it more Fusion 13 ready. Having both Fusion 12 and 13 templates available help show case the needed differences. That said, the Fusion 13 work is a ticket that we need to create and prioritize.

2023-04-13 19:37 UTC, nywilken commented on example/http/debian/preseed.cfg
That is a good addition. I can roll that in. Thanks for the example.

2023-04-13 19:39 UTC, nywilken commented on example/pkrvars/debian/fusion-12.pkrvars.hcl
How do you feel about holding on removing the example until the fusion 13 driver (it doesn't exist yet) becomes the default?

2023-04-13 19:57 UTC, tenthirtyam commented on example/pkrvars/debian/fusion-12.pkrvars.hcl
Fine by me!

2023-04-14 17:01 UTC, tenthirtyam approved these changes
LGTM! :shipit:

2023-04-14 19:06 UTC, lbajolet-hashicorp approved these changes
Just left a little nit, but aside from that, LGTM!

2023-04-14 19:06 UTC, lbajolet-hashicorp commented on example/README.md
> + - variables.pkr.hcl contains a set of defined variables need for building the image.
```suggestion
 - variables.pkr.hcl contains a set of defined variables needed for building the image. 
```

2023-04-17 20:17 UTC, merged