Add instructions to get VMWare Player working on Linux
hashicorp/packer-plugin-vmware pull request #39
Opened 2021-09-20 20:15 UTC by sbrownjc

In attempting to get packer working with VMWare Workstation Player on Linux, I had a lot of trouble until I found the information scattered about the internet, and then found this closed PR, whose instructions mirrored exactly what I'd done to get Workstation Player 16 running with Packer: https://github.com/hashicorp/packer/pull/3451

This closed issue https://github.com/hashicorp/packer/issues/1102 references this (lost?) commit: https://github.com/hashicorp/packer/commit/c5ec92c88bb154bd317aec5b81ba6cf9e4dff9c4 which would have saved me much time if I could have seen it, so I'm making this PR to bring the information from https://github.com/hashicorp/packer/pull/3451 in and up-to-date.

2021-09-20 20:15 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-vmware?pullRequest=39)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-vmware?pullRequest=39)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-vmware?pullRequest=39).</sub>

2022-07-27 17:56 UTC, nywilken commented
👋 I still think that this [comment](https://github.com/hashicorp/packer/pull/3451#issuecomment-366091480) is still very relevant. That said, @tenthirtyam do you have some thoughts on how we should be capture this. 

Is this something that you have documented within your vmware-samples repo?

2022-07-27 18:09 UTC, tenthirtyam commented
Hey, @nywilken -

I don't have anything in [that](https://github.com/vmware-samples/packer-examples-for-vsphere) project that uses the `vmware-iso` builder. 

I do use the `vmware-iso` builder for VMware Fusion and VMware Workstation in the https://github.com/vmware/photon-packer-templates project to create Photon images for Vagrant. However, VMware Player is not included/tested.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

2022-07-27 18:17 UTC, tenthirtyam commented
I've added some comments to this PR for context, clarity, and correctness.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

2022-08-09 01:18 UTC, tenthirtyam requested changes
@nywilken @sbrownjc, I've recommended some changes before merge.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

2022-08-09 01:18 UTC, tenthirtyam commented on docs/builders/index.mdx
> +## VMware (Workstation) Player on Linux
"VMware Workstation Player on Linux"

2022-08-09 01:18 UTC, tenthirtyam commented on docs/builders/index.mdx
> +Unfortunately just installing VMware Player is not quite enough to be able to
"VMware Workstation Player"

2022-08-09 01:18 UTC, tenthirtyam commented on docs/builders/index.mdx
> +Finally, if you installed a version of VMware player newer than 7.0, you must
I would remove the versioning. Ideally the plugin should support only those versions supported by VMware per the lifecycle matrix. See project README.

2022-08-10 21:53 UTC, sbrownjc commented
@tenthirtyam Thanks for the review comments, I've updated the docs accordingly.

2022-08-11 00:45 UTC, tenthirtyam commented
Thanks! I'll review the updates tomorrow for Wilken and provide and update.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

2022-08-11 01:41 UTC, tenthirtyam approved these changes
LGTM! 🚀 

cc @nywilken

2022-08-12 17:20 UTC, nywilken commented
@tenthirtyam thanks for the thoughts and review on this PR, and @sbrownjc thanks for updates. The changes look good me me. We just need to have you sign the CLA so that I can merge these changes in. 

If you have already accepted the CLA please make sure that the email used in your commits match the email you signed the CLA with and that the signing email is your primary GitHub email. The CLA bot only checks against the user's primary GitHub email.

2022-09-28 03:52 UTC, tenthirtyam commented
Hi @sbrownjc -  could you resolve the issue with signing the HashiCorp CLA? This will help expedite your valuable updates.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

2022-10-07 03:58 UTC, tenthirtyam commented
Hi @sbrownjc - could you resolve the issue with signing the HashiCorp CLA? This will help expedite your valuable updates.

Ryan Johnson
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

2022-10-17 18:23 UTC, sbrownjc commented
Hi @tenthirtyam, I'm sorry for the delay, I was waiting on a response from legal since I posted using my work GH account.

If possible, I would like to submit this work outside of a CLA, following section 7 of the CLA:
> Should You wish to submit work that is not Your original creation, You may submit it to HashiCorp separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which you are personally aware, and conspicuously marking the work as "Submitted on behalf of a third-party: [named here]".

This work is being Submitted on behalf of a third-party: [Anand Kumria](https://github.com/akumria)

2022-10-17 23:28 UTC, tenthirtyam commented
cc @nywilken for submission state review.

2023-01-30 17:14 UTC, nywilken commented
@sbrownjc @tenthirtyam apologies for not getting back much sooner. In speaking with our legal team the author of the change must still sign the CLA in order to make the contribution on behalf of another contributor under section 7. Unfortunately that means I will not be able to merge in these changes unless the CLA is signed.

I'm going to close this PR given the time I kept everyone waiting. If you wish to reopen with your personal GH and sign the CLA I would be glad to merge it right away. 

Thank you @tenthirtyam for your help here.

2023-01-30 17:14 UTC, closed without merging